language: node_js
os: linux
node_js:
  - "15"

script:
  - npm install
  - npm run test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  cleanup: true
